name: vitaminav
description: A multi-platform mobile app for spiritual readings.
publish_to: 'none'

version: 1.1.0+18

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite:
  path:
  shared_preferences:
  flutter_svg:
  flutter_html:
  url_launcher:
  share:
  flutter_feather_icons:
  flutter_local_notifications: ^3.0.2
  timezone: ^0.5.9
  flutter_native_timezone: ^1.0.4
  notification_permissions: ^0.4.8
  package_info: ^0.4.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/via_crucis/

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: google_fonts/RobotoSlab-Regular.ttf
        - asset: google_fonts/RobotoSlab-Bold.ttf
          weight: 700
        - asset: google_fonts/RobotoSlab-Thin.ttf
          weight: 200

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"